# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companions', models.ManyToManyField(null=True, related_name='plans', to='travel_buddy.User')),
                ('planner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to='travel_buddy.User')),
            ],
        ),
    ]
